version: '3'

volumes:
  mysql:
  elastic:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    restart: always
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
      # - "127.0.0.1:9300:9300"
    environment:
      VIRTUAL_PORT: 9200
      VIRTUAL_HOST: elasticsearch.poma.in
      LETSENCRYPT_HOST: elasticsearch.poma.in
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      cluster.name: docker-cluster
      network.host: 0.0.0.0
      discovery.type: single-node
      xpack.license.self_generated.type: basic
      xpack.monitoring.collection.enabled: "true"

  mysql:
    image: mysql:8.0.22
    container_name: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: henry